spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto:  update
  datasource:
    url: jdbc:h2:./devdb
    username: sa


server:
  port: 8083



